name: Frontend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to latest version
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run lint
        run: npm run lint
        working-directory: frontend

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to latest version
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend
        env:
          NODE_ENV: production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4 # Fixed deprecated version
        with:
          name: frontend-dist
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Download build artifact
        uses: actions/download-artifact@v4 # Fixed deprecated version
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to latest version
        with:
          node-version: "18"

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify-cli deploy --prod --dir=frontend/dist --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
